---
title: Read the harvesting data
author: "Moises Exposito-Alonso (moisesexpositoalonso@gmail.com)"
date: '`r Sys.Date()`'
output:
  html_document: default
  # pdf_document: default
  
---

<!-- Define global options for knitr -->
```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  #fig.width=12, fig.height=8, fig.path='Figs/',
  # echo=FALSE, warning=FALSE, message=FALSE
  root.dir='../'
  )
```

```{r, setup package}
library(dplyr);library(tidyr)
library(devtools)

load_all("~/mexposito/moiR/")
# library(moiR)
load_all(".")
# library(field)

wannaoverwrite=F
```


```{r}
####################################################################################
## read harvesting info

# tueh <- make_data_harvest(location="tuebingen")
# madh <- make_data_harvest(location="madrid")
# harvest<-rbind(madh,tueh) #### <<- need to change when tuebingen is annotated
# harvest<-(madh) #### <<- need to change when tuebingen is annotated
# harvestraw<-harvest
# devtools::use_data(harvestraw,overwrite = F)  #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< UPDATE THIS WHEN ALL IMAGES ARE LABELED!
# write.tsv(harvestraw,file='../data-raw/harvestraw') 

data(harvestraw)
harvest=harvestraw
head(harvest)
tail(harvest)
dim(harvest)

# merge
data("genoreps")
head(genoreps)

harvest= merge(harvest,genoreps, by.x=c('qp','pos','site','ptype'),by.y=c('qp','pos','site','indpop'),all.y=T) %>%  ### NOTE ALSO THAT CAN BE SEVERAL PICTURES FOR A SINGLE POT!
  rename(indpop=ptype)
  # important to consider that the indpop or population type could be either that the image was mistaken or that when I labeled them there was r1 and then it was actually only r

head(harvest)
tail(harvest)


# put in the number column NA when it is an individual replicate
harvest$num[harvest$indpop == 'i']<-NA
harvest$num[harvest$num == 'missin']<-(-9)
harvest$num[harvest$num == '']<-(-9)
harvest$num<-as.character.factor(harvest$num)

# add quality flag
harvest$Harv.q <- 0
harvest$Harv.q[ !is.na(harvest$pathimage) ] <-1

# check missing data and so on
unique(harvest$Harv.q)
unique(harvest$num)

head(harvest)
tail(harvest)
dim(harvest)

## save harvestclean
harvestclean=harvest
names(harvestclean)
if(wannaoverwrite==T) devtools::use_data(harvestclean,overwrite = T) # this includes also path to image

## save but remove some columns
head(harvest)
names(harvest)
dim(harvest)
harvest=harvest %>% 
  select(-pathimage, -datelabeled) %>%  # remove these unimportant columns
  rename(Harv.organ=organ,   # rename some
         Harv.num=num,
         Harv.area=totarea,
         Harv.sk=sk,
         Harv.bp=bp,
         Harv.ep=ep)

print('The first lines of data index of harvest:')
print(head(harvest,n=5))
print("Rows without data:")
table(is.na(harvest$totarea))

if(wannaoverwrite==T) devtools::use_data(harvest,overwrite = T)


harvest %>% filter(Harv.organ=='i') %>%
ggplot() +
  geom_histogram(aes(x=Harv.area,group=water,fill=water,alpha=0.3)) + 
  scale_fill_manual(values = c("h"="navy","l"="red3"))+facet_grid(site~indpop)+
  theme_bw() +
  xlab('Total segmented inflorescence area (# pixels)') + 
  scale_alpha(guide = 'none') -> p1
p1

set_project_dir()
save_plot(filename = 'figs/Figure_inflorescence_distribution.pdf',base_height = 3,base_width = 6, plot=p1)


```

## Model to predict harvested organ from image analysis
```{r}

ggplot(harvestclean) + 
  geom_point(aes(x=ep, y=bp,group=organ, color=organ),alpha=0.5)
library(randomForest)
modorgan<-randomForest(data=harvestclean, organ ~ ep + bp + totarea + sk ,
                       importance=T,
                       na.action=na.omit)

predict(modorgan) %>% str()
(predict(modorgan) %>% as.character())
predict(modorgan) 
validation=data.frame(pred=(predict(modorgan) %>% as.character()), real=(harvestclean$organ %>% na.omit()))

table(validation$pred == validation$real ) / sum(table(validation$pred == validation$real )
)

harvestclean
which(validation$pred != validation$real)

harvestclean %>% mutate(index=row.names(harvestclean)) %>%
  filter(!is.na(pathimage)) %>%
  filter(index %in% which(validation$pred != validation$real) )  
 

```

