---
title: Estimate seeds for absolute fitness using approximate allometries
author: "Moises Exposito-Alonso (moisesexpositoalonso@gmail.com)"
date: '`r Sys.Date()`'
output:
  html_document: default
---


```{r, setup package}
library(dplyr)
library(tidyr)
library(devtools)

library(moiR)
devtools::load_all('.')

```

# manually count fruits
```{r manually count fruits}

set.seed(1)

# get a good representation of images based on the space of skeleton, branching points, etc
data(harvest)


harvest[,c('Harv.sk','Harv.area','Harv.bp','Harv.ep')] %>% 
  na.omit() %>%
prcomp(.) -> pcinflorescence

summary(pcinflorescence) 


ggpca(pcinflorescence)
ggplot(harvest)+
  geom_point(aes(Harv.area, Harv.sk))


# Subset the relevant variables
harvest[,c('pathimage','Harv.sk','Harv.area','Harv.bp','Harv.ep')] %>% 
  na.omit()-> hnona
  
# # generate groups based on quantiles in the harvest area
# hnona$group=cut(hnona$Harv.area, breaks=
#                   quantile(hnona$Harv.area,probs = c(0,0.2,0.4,0.6,0.8,1)),labels = FALSE)
# hnona$group %>% unique
# # check that it worked
# plot(hnona$Harv.area ~ hnona$group)
# 
# # Sample 50 images per harvest area range
# selectionimages=tapply(hnona$pathimage,hnona$group, function(i) sample(i,size=50) ) %>% unlist() %>%
#   sample(.,replace = F)
#   # resample so they are not sorted by size. then I can count any number and will
#   # have a good representation
# 
# # write
# write.table(file='data-raw/tocountfruits_n1.tsv',data.frame(pathimage=selectionimages,fruitcount=NA),quote=F, row.names=F)


### Direclty the smallest and the largest can be counted, and then we assume a linear relationship 
### I think counting 250 is too much, since some plants have some thousands of fruits.

field.i=filter(field,indpop=='i')

field.i[field.i$Harv.area > quantile(field.i$Harv.area, probs = 0.999,na.rm=T),] %>% 
  na.omit %>% select(pathimage) %>%unlist ->
  high
field.i[field.i$Harv.area < quantile(field.i$Harv.area, probs = 0.001,na.rm=T),] %>% 
  na.omit%>% select(pathimage) %>%unlist ->
  low

# tocountextremes=c(high,low) %>% sample(.,replace = FALSE)
tocountextremes=c(low) %>% sample(.,replace = FALSE) # high cannot be counted direclty in the image
tocountextremes<-data.frame(pathimage=tocountextremes,nfruits=NA)

### Read the manually counted
# write.table(file='data-raw/tocountfruits_extremes.tsv',tocountextremes,quote=F, row.names=F)
set_project_dir()
lowcounted=read.table(file='data-raw/tocountfruits_extremes.tsv',header = TRUE,stringsAsFactors = FALSE)
  # there are two that are rosettes
lowcounted=filter(lowcounted, nfruits !='rosette')

### the high needed to be counted manually taking the envelopes
highcounted=read.table(file='data-raw/tocountfruits_extremes_manualhandling.tsv',header=TRUE,stringsAsFactors = FALSE)
  # '../data/field_madrid_harvesting/2016_513/P1160487.JPG' this is qp 311, correct it!

# Just to find those that I counted
dplyr::filter(field,site=='tuebingen',tray=='321',pos=='a5')

filter(field,pathimage=='../data/field_madrid_harvesting/2016_513/P1160487.JPG')


### Merge with Field
counted=rbind(lowcounted,highcounted)

fruitcounted<-merge(field, counted, by='pathimage') 

devtools::use_data(fruitcounted)

```



# build relationsihp area to fruit
```{r build relationsihp area fruit}


.fruitpredictor<-function(fruitcounted){

mod.sk=lm(fruitcounted$nfruits ~ fruitcounted$Harv.sk ) 
mod.area<-lm(fruitcounted$nfruits ~ fruitcounted$Harv.area ) 
mod.bp<-lm(fruitcounted$nfruits ~ fruitcounted$Harv.bp ) 
mod.ep<-lm(fruitcounted$nfruits ~ fruitcounted$Harv.ep ) 

plot(fruitcounted$nfruits ~ fruitcounted$Harv.sk ,ylab='Manually counted fruits', xlab='Inflorescence skeleton size (# pixels)')
abline(mod.sk)

mod.all<-lm(data=ff, nfruits ~ Harv.sk + Harv.area+ Harv.bp +Harv.ep ) 
print(summary(mod.all))

return(list(sk=mod.sk, area=mod.area,bp=mod.bp, ep=mod.ep,all=mod.all))

}
.fruitpredictor(fruitcounted)  

fruitpredictor<-function(dat,from){
     if(from=='sk') predict(object = .fruitpredictor[['sk']],newdata = dat )
else if(from=='area') predict(object = .fruitpredictor[['area']],newdata = dat )
else if(from=='bp') predict(object = .fruitpredictor[['bp']],newdata = dat )
else if(from=='ep') predict(object = .fruitpredictor[['ep']],newdata = dat )
else if(from=='all') predict(object = .fruitpredictor[['all']],newdata = dat )

  
}


```


# manually count seeds
```{r manually count seeds}
# Took 50 fruits from Col-0 plants at different maturation times and well watered and relatively badly watered.
# seedcounts<-c(21,50,14,27,45,38,44,40,50,50,37)
# mean(seedcounts)
# sd(seedcounts)

# Took fruits from the harvested plants to get an estiamte directly in the field experiment
seedcounts=c(19,17,18,43,48,19,31,22,30,36)
mean(seedcounts)
sd(seedcounts)
  

```

```{r build the relationship fruit-seed}

```

