---
title: "Fitness distributions"
author: "Moises Exposito-Alonso (moisesexpositoalonso@gmail.com)"
date: '`r Sys.Date()`'
output:
  html_document: default
---


## Packages set up and loading data

```{r setup, include=F}
library(knitr)
library(dplyr,tidyr)
library(ggplot2);library(cowplot)
library(devtools)
library(RColorBrewer)
# library(moiR)
load_all("~/moiR")
load_all(".")

data(field)
data(field.s)

```


## PLots of fitnes
```{r}


ggplot(field.s) +
  geom_histogram(aes(x=Fitness,group=water,fill=water,alpha=0.3)) + 
  scale_fill_manual(values = c("h"="navy","l"="red3"))+
  facet_grid(site~indpop)+
  theme_bw() +
  xlab('Lifetime fitness (% survival x # inflorescence pixels)') + 
  scale_alpha(guide = 'none') -> p1
p1

ggplot(field.s) +
  geom_histogram(aes(x=Fecundity.byind,group=water,fill=water,alpha=0.3)) + 
  scale_fill_manual(values = c("h"="navy","l"="red3"))+
  facet_grid(site~indpop)+
  theme_bw() +
  xlab('Fecundity ( # inflorescence pixels)') + 
  scale_alpha(guide = 'none') -> p2
p2

ggplot(field.s) +
  geom_histogram(aes(x=Survival.fruit,group=water,fill=water,alpha=0.3)) + 
  scale_fill_manual(values = c("h"="navy","l"="red3"))+
  facet_grid(site~indpop)+
  theme_bw() +
  xlab('Probability of survival to reproduction') + 
  scale_alpha(guide = 'none') -> p3
p3

ggplot(field.s) +
  geom_histogram(aes(x=Survival.num,group=water,fill=water,alpha=0.3)) + 
  scale_fill_manual(values = c("h"="navy","l"="red3"))+
  facet_grid(site~indpop)+
  theme_bw() +
  xlab('Number of individuals that survived outof 30 (only relevant for population replicate)') + 
  scale_alpha(guide = 'none') -> p4
p4


# set_project_dir()
# save_plot(filename = 'figs/Figure_inflorescence_distribution.pdf',base_height = 6,base_width = 6, plot=p1)


```


################################################################################

