---
title: "Flowering analysis of the 1001G fiel experiment"
author: "Moises Exposito-Alonso (moisesexpositoalonso@gmail.com)"
date: '`r Sys.Date()`'
output:
  html_document: default
  # html_notebook: default
  pdf_document: default
---


    ## Packages set up

```{r setup, include=FALSE}
library(knitr)
library(dplyr,tidyr)
library(ggplot2);library(cowplot)
library(devtools)
library(RColorBrewer)
# library(moiR)
source("~/ebio/abt6_projects9/ath_1001G_image_pheno/experiment_218_droughtgwa/droughtfunctions.R")
load_all("~/mexposito/moiR/")
load_all(".")

```

## load data sets

```{r data}
#data(field)
#dim(field)
# head(field)
```

## Verify replicability
```{r}
data(veggyraw)

## check duplicated image pots
veggyraw=mutate(veggyraw, indexrep=paste(site,qp,pos,day,sep='_'))

dim(veggyraw[duplicated(veggyraw$indexrep),]) # There are 790 in total from both experiments

## Run the test for replicability
library(MCMCglmm)
lmm=MCMCglmm(data=veggyraw[duplicated(veggyraw$indexrep),], countgreen ~1, random = ~ indexrep, family = 'poisson',verbose=F)
print ( h2MCMC(lmm,randomname = 'indexrep') )

```

## Plot trends
```{r}
data(veggypot)
names(veggypot)

# Generate all trends
ggplot(veggypot) + geom_line(aes(y=count,x=day,group=potindex, color=factor(id)),alpha=0.1 ) + theme(legend.position="none")
# ggplot(veggypot) + geom_line(aes(y=countred,x=day,group=potindex, color=factor(id)),alpha=0.1 ) + theme(legend.position="none")

```

## Model trends
```{r}

glm1=glm(data=veggypot, count ~ poly(day,3), family = 'poisson')


# fixform<-formula(green ~  poly(day, 2,  raw = TRUE))  ### FOLLOWING THE GREENHOUSE EXPERIMENT
# randomform<-formula(~ idh(1 + poly(day, 2, raw = TRUE)):id + qppot + position)
# m1diii_qppos <- MCMCglmm(fixed=fixform, randomform, data = ggdecay,  family="poisson",
#                          pr=T,pl=T,nitt = 10000,burnin = 1000,saveXL=T,saveZ=T,saveX=T,verbose=F , singular.ok=T)  #this works!

# veggypot$count=as.integer(veggypot$count)
# glmm2=MCMCglmm(data=veggypot, 
#                count ~ poly(day,3),
#                random= ~ idh(1 + poly(day, 3)):potindex, 
#                family = 'poisson')
# 
# stargazer::stargaze(glm1,type='text')

############### <<<<<<<<<<<<<<< CONTINUE HERE. IT WOULD BE NICE TO HAVE A PLATEAU VALUE, A POINT OF 0, A SLOPE ... 

```

