---
title: Growth trajectories exploration, variance proportion
  missing pots
author: "Moises Exposito-Alonso (moisesexpositoalonso@gmail.com)"
date: '`r Sys.Date()`'
output:
  html_document: default
  #pdf_document: default
  #html_notebook: default
---

## Packages set up and loading data

```{r setup, include=F}
library(knitr)
library(dplyr,tidyr)
library(ggplot2);library(cowplot)
library(devtools)
library(RColorBrewer)
# library(moiR)
load_all("~/moiR")
load_all(".")

data(veggy)
data(veg)


```

##  Plotting the sigmoidal curves of 1000 pots 

```{r}

vegh<- veg %>% dplyr::filter(ger.a != "NA") %>% dplyr::sample_n(size = 1000) 

plot( ylab='Predicted # pixels',xlab='Days of experiment',
  ylim=c(0,50000),
  y=
getsigmoid(
  a= substrRight(vegh$ger.a,lastpos = 4,giveright = F)[2],
  b= substrRight(vegh$ger.b,lastpos = 4,giveright = F)[2],
  c= substrRight(vegh$ger.c,lastpos = 4,giveright = F)[2]
),
x=1:40,
type='l'
)
for( i in 1:nrow(vegh)){
lines(  y=
getsigmoid(
  a= substrRight(vegh$ger.a,lastpos = 4,giveright = F)[i],
  b= substrRight(vegh$ger.b,lastpos = 4,giveright = F)[i],
  c= substrRight(vegh$ger.c,lastpos = 4,giveright = F)[i]
),
x=1:40,
col=transparent('black')
)
}

```

## Calculate various variance proportions of the modeled trajectories.

```{r calculate}

library(lme4)
library(MCMCglmm)

veg %>%
  filter(redsum < 1e4) %>%
  # filter(greensum >1e4) %>%
  mutate(
  a= removetail(ger.a,4),
  b= removetail(ger.b,4),
  c= removetail(ger.c,4)
  ) %>%
lmer(formula = a ~ (1|id) + (1|water)+ (1|site) + (1|indpop)  ) -> lmod 
lmod %>% randomvariance(.,var =c('id','water','site',"indpop") )

```
```{r}
veg %>%
  filter(redsum < 1e4) %>%
  # filter(greensum >1e4) %>%
  mutate(
  a= removetail(ger.a,4),
  b= removetail(ger.b,4),
  c= removetail(ger.c,4)
  ) %>%
lmer(formula = b ~ (1|id) + (1|water)+ (1|site) + (1|indpop)  ) -> lmod
lmod %>% randomvariance(.,var =c('id','water','site',"indpop") )

```

```{r}

veg %>%
  filter(redsum < 1e4) %>%
  # filter(greensum >1e4) %>%
  mutate(
  a= removetail(ger.a,4),
  b= removetail(ger.b,4),
  c= removetail(ger.c,4)
  ) %>%
lmer(formula = c ~ (1|id) + (1|water)+ (1|site) + (1|indpop)  ) -> lmod 
lmod %>% randomvariance(.,var =c('id','water','site',"indpop") )

```

Not very satisfactory. Most of the effect is about individual versus population replicates

### Calculate variance in a per-experiment treatment basis 

```{r}
veg %>%
  filter(redsum < 1e4) %>%
  # filter(greensum >1e4) %>%
  mutate(
  a= removetail(ger.a,4),
  b= removetail(ger.b,4),
  c= removetail(ger.c,4),
  l=removetail(lin.0)
  ) %>%
  filter(water=='h', indpop=='i', site=='madrid') %>%
# lmer(formula = b ~ (1|id) ) -> lmod 
# lmer(formula = a ~ (1|id) ) -> lmod 
# lmer(formula = c ~ (1|id) ) -> lmod 
# lmer(formula = greensum ~ (1|id) ) -> lmod
# lmer(formula = redsum ~ (1|id) ) -> lmod
lmer(formula = l ~ (1|id) ) -> lmod
lmod %>% randomvariance(.,var =c('id') )


```



```{r, session info, echo=FALSE}
sessionInfo()

```

