\newline Moises Exposito-Alonso^1^\textsuperscript{*}  , 
  Rocío Gómez Rodríguez^2^, 
  Cristina Barragán^1^, 
  Giovanna Capovilla^1^,
  Eunyoung Chae^1^,
  Jane Devos^1^,
  Ezgi Dogan^1^,
  Claudia Friedemann^1^,
  Caspar Gross^1^,
  Patricia Lang^1^,
  Derek Lundberg^1^,
  Belén Méndez-Vigo^3^,
  Vera Middendorf^1^,
  Jorge Kageyama^1^,
  Talia Karasov^1^,
  Sonja Kersten^1^,
  Sebastian Petersen^1^,
  Leily Rabbani^1^,
  Julian Regalado^1^,
  Beth Rowan^1^,
  Danelle Seymour^1^,
  Efthymia Symeonidi^1^, 
  Rebecca Schwab^1^,
  Diep Tran^1^,
  Kavita Venkataramani^1^,
  Anna-Lena Van de Weyer^1^,
  Ronja Wedegärtne^1^,
  Frank Weiss^1^,
  Rui Wu^1^,
  Wanyan Xi^1^,
  Maricris Zaidem^1^,
  Wangsheng Zhu^1^,
  Fernando García Arenal^2^,
  Carlos Alonso Blanco^3^,
  Xavier Picó^4^,
  Hernán A. Burbano^1^,
  Oliver Bossdorf^5^,
  Detlef Weigel^1^.
  \newline 
  \newline \textsuperscript{1} Max Planck Institute for Developmental Biology, Tübingen, Germany    
  \newline \textsuperscript{2} Centre for Plant Biotechnology and Genomics, Technical University of Madrid, Pozuelo de Alarcón, Spain 
  \newline \textsuperscript{3} National Centre of Biotechnology, Cantoblanco, Madrid, Spain  
  \newline \textsuperscript{4} Doñana Biological Station, Sevilla, Spain
  \newline \textsuperscript{5} University of Tübingen, Tübingen, Germany
  \newline \textsuperscript{*} correspondence to moisesexpositoalonso@gmail.com
  \newline \newline \newline \newline \newline \newline 
  
  
  
  
  ---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    # template: ms_template.tex
    template: manuscript_template.tex
title: "A Pandoc Markdown Article Starter and Template"
thanks: "correspondence to moisesexpositoalonso@gmail.com"
author:
- name: Moises Exposito-Alonso
  affiliation: Max Planck Institute
abstract: "This document provides an introduction to R Markdown, |argues for its..."
keywords: "pandoc, r markdown, knitr"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
#fontfamily: mathpazo
#fontsize: 11pt
# spacing: double
bibliography: references.bib
biblio-style: apsr
---


"*Moises Exposito-Alonso, Rocio Gomez Rodriguez, Cristina Barragan, Oliver Bossdor, Giovana Capovila, Enyoung Chae, Jane Devos Ezgi Dogan, Claudia Friedeman, Caspar Gross, Patricia Lang, Derek Lundberg, Belén Méndez-Vigo, Vera Middendorf, Jorge Kagayema, Talia Karasov, Sonja Kersten, Sebastian Petersen, Leily Rabani, Julian Regalado, Beth Rowan, Danelle Seymor, Efftimia Simeonidi, Rebecca Schwab, Diep Tran, Kavita Venkataramani, Anna-Lena Van de Weyer, Ronja Wedegärtner, Frank Weiss, Rui Wu, Wanyan Xi, Mari Cris Zaidem, Wansheng Zhu, Carlos Alonso Blanco, Xavier Pico, Hernan A. Burbano, Oliver Bossdorf, Detlef Weigel*;  correspondence to: moisesexpositoalonao@gmail.com"


https://support.rstudio.com/hc/en-us/community/posts/201113713-Multiple-authors-in-Rmarkdown-
 Author 1 \textsuperscript{1}, Author 2 \textsuperscript{1}, Author 3 \textsuperscript{2} \ \newline \newline \textsuperscript{1} Department of Biology, University of Vermont \ \textsuperscript{2} Vermont Genetics Network, University of Vermont




<!-- ## Equations -->

<!-- The deterministic part of the model is defined by this **in-line equation** as -->
<!-- $\mu_i = \beta_0 + \beta_1x$, and the stochastic part by the **centered equation**: -->

<!-- $$ \frac{1}{\sqrt{2\pi}\sigma}e^{-(x-\mu_i)^2/(2\sigma^2)} $$ -->

<!-- ## Tables -->

<!-- ```{r kable, echo=FALSE} -->
<!-- library(knitr) -->

<!-- x <- rnorm(100) -->
<!-- y <- 2*x + rnorm(100) -->
<!-- out <- lm(y ~ x) -->
<!-- kable(summary(out)$coef, digits=2, caption="This is a GLM summary table.") -->
<!-- ``` -->

<!-- ```{r xtable, results="asis", echo=FALSE, eval=FALSE, message=FALSE} -->
<!-- library(xtable) -->
<!-- # tab <- xtable(summary(out)$coef, digits=c(0, 2, 2, 1, 2), -->
<!-- #               caption="This is a GLM summary table.") -->
<!-- # print(tab, type="latex") -->
<!-- ``` -->

<!-- ## Plots -->

<!-- ```{r carDataPlot, echo=FALSE, fig.cap="Relationship between x and y. The solid line is least-squares linear regression.", fig.width=4, fig.height=4} -->
<!--   plot(x, y) -->
<!--   abline(out) -->
<!-- ``` -->
<!-- ## Citations -->

<!-- The relationship was first described by -->
<!-- `r citet("10.1111/j.1461-0248.2005.00827.x")`. However, there are also opinions -->
<!-- that the relationship is spurious `r citep("10.1111/j.2041-210x.2012.00264.x")`. -->
<!-- We used R for our calculations `r citep(citation())`, and we used package `knitcitations` `r citep(citation("knitcitations"))` to make the bibliography. -->

<!-- `r citet("Salguero-Gomez2015-nn")` -->



```{r, warning=FALSE, message=FALSE, echo=FALSE}
# knitcitations::write.bibtex(file="bibliography/references.bib")
# bibtex::read.bib(file="references.bib")

```
